### ISSUE TITLE
use of SECURITY_DESCRIPTOR

### ISSUE THREAD

**Issue by aryef** [sebkirche/mailslot#1]
Hi,

I am trying to implement usage of type SECURITY_DESCRIPTOR in function 
CreateMailslot  instead of ulong; namely : 
CreateMailslot(ref string mailslotName, ulong nMaxMessageSize, ulong lReadTimeout,  SECURITY_DESCRIPTOR securityAttributes).

Security descriptor apparently should  be a structure  with the following fields ( a sample from C#):
    public int nLength;
    public IntPtr lpSecurityDescriptor;
    public int bInheritHandle;

Unfortunately all my efforts to create  mailslot with this new variable failed on error 87 (invalid parameter). 
I'll very appreciate if you have a solution for this.
Arye

**Comment by aryef** [comment]
Update: 
Passing the correct size of structure makes the trick.
Here you can find  PB code to calculate object size to pass to any external API: [(http://nntp-archive.sybase.com/nntp-archive/action/article/%3C368_EQcAKQYMBHA.275%40forums.sybase.com%3E )]
I tested it and after a few minor code fixes it works just fine.

Another possible way is by utilizing C/C++ utility to do the same : [(https://wiki.scn.sap.com/wiki/display/SYBPB/Size+of+API+Structure+Utility]

**Comment by sebkirche** [comment]
Thanks for your contribution (I have close to no contributors !)
For my curiosity, what is the context of your usage of Mailslot in PB?

**Comment by aryef** [comment]
Hello Sébastien,
We aim to build a lightweight bidirectional instant communication system between our legacy PB-based systems and new .NET systems. In the past we tried to use various approaches but all were either too slow or unstable or prone to the environment or very technically difficult.
The Mailslot-based approach seems to  be the best one being very fast, very stable and very simple. Your project was very helpful for us to get to this point.
I'll submit a pull request with our proopsed change implementing SECURITY_DESCRIPTOR usage.
And thank you for sharing your project!
